name: "PR Title Checker"
on: pull_request_target

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          title-regex: "((NG)-[0-9]+|(feat:|tests:|misc:))\\s.{5,50}$"
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "This is just an example. Failed regex: `%regex%`!"
          on-succeeded-regex-dismiss-review-comment:
            "This is just an example. Success!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
